<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GenAIPlatform.Application.Agentic\GenAIPlatform.Application.Agentic.csproj" />
    <ProjectReference Include="..\..\src\GenAIPlatform.Application.Core\GenAIPlatform.Application.Core.csproj" />
    <ProjectReference Include="..\..\src\GenAIPlatform.Application.Evaluations\GenAIPlatform.Application.Evaluations.csproj" />
    <ProjectReference Include="..\..\src\GenAIPlatform.Application.Generation\GenAIPlatform.Application.Generation.csproj" />
    <ProjectReference Include="..\..\src\GenAIPlatform.Application.Knowledge\GenAIPlatform.Application.Knowledge.csproj" />
    <ProjectReference Include="..\..\src\GenAIPlatform.Application.Usage\GenAIPlatform.Application.Usage.csproj" />
    <ProjectReference Include="..\..\src\GenAIPlatform.Domain\GenAIPlatform.Domain.csproj" />
    <ProjectReference Include="..\..\src\GenAIPlatform.Infrastructure\GenAIPlatform.Infrastructure.csproj" />
  </ItemGroup>

</Project>
